### ISSUE TITLE
fails to install via pip

### ISSUE THREAD

**Issue by carchrae** [mk270/json-table-schema-python#4]

**Comment by carchrae** [comment]
i hope this is the right place to report this.  my apologies if not.

**Comment by mk270** [comment]
thanks - obviously we've just broken it - any idea what's wrong?

**Comment by mk270** [comment]
turns out the package was overwritten by a malformed copy of itself; I've put the original back

**Comment by carchrae** [comment]
yeah, it looked like the setup.py file was missing.  i installed 0.2 by cloning from git, then installing.  then the problem with https://github.com/okfn/messytables/pull/131 went away.

**Comment by davidread** [comment]
json-table-schema still won't install from PyPI, so it appears to still be an issue. I'm concerned that this leaves `pip install messytables` broken.
```
$ pip install -e messytables
...
Downloading/unpacking json-table-schema (from messytables==0.14.5)
  Downloading json-table-schema-0.2.linux-i686.tar.gz
  Running setup.py egg_info for package json-table-schema
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/src/datapusher/build/json-table-schema/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/src/datapusher/build/json-table-schema/setup.py'
```
Like @carchrae I managed to install it from source.

**Comment by mk270** [comment]
I've added Paul Walsh as a maintainer on PyPI - if I need to do anything else, please tell me what you need.

**Comment by scraperdragon** [comment]
I'm noticing there's now a source release on PyPI and I'm not getting that error - can people confirm whether this is dealt with? @davidread @carchrae ?

PS: If this is resolved, we should close https://github.com/okfn/messytables/pull/131 without merging.

**Comment by davidread** [comment]
Still broken for me. How are you doing it differently, @scraperdragon ?
```
$ virtualenv testenv
New python executable in testenv/bin/python
Installing distribute.............................................................................................................................................................................................done.
Installing pip...............done.

$ testenv/bin/pip install messytables
Downloading/unpacking messytables
  Downloading messytables-0.14.5.tar.gz
  Running setup.py egg_info for package messytables

Downloading/unpacking xlrd>=0.8.0 (from messytables)
  Downloading xlrd-0.9.3.tar.gz (178Kb): 178Kb downloaded
  Running setup.py egg_info for package xlrd

Downloading/unpacking python-magic==0.4.6 (from messytables)
  Downloading python-magic-0.4.6.tar.gz
  Running setup.py egg_info for package python-magic

Downloading/unpacking chardet==2.1.1 (from messytables)
  Downloading chardet-2.1.1.tar.gz (178Kb): 178Kb downloaded
  Running setup.py egg_info for package chardet

Downloading/unpacking python-dateutil>=1.5.0,<2.0.0 (from messytables)
  Downloading python-dateutil-1.5.tar.gz (233Kb): 233Kb downloaded
  Running setup.py egg_info for package python-dateutil

Downloading/unpacking json-table-schema (from messytables)
  Downloading json-table-schema-0.2.linux-i686.tar.gz
  Running setup.py egg_info for package json-table-schema
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/src/test/testenv/build/json-table-schema/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/src/test/testenv/build/json-table-schema/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /src/test/testenv/build/json-table-schema
Storing complete log in /home/co/.pip/pip.log
```

**Comment by scraperdragon** [comment]
when I run I'm getting 

```
Downloading/unpacking json-table-schema (from messytables)
  Downloading json-table-schema-0.2.tar.gz
```

Not sure what the difference between this and the `linux-i686` versions are.

**Comment by davidread** [comment]
Ah, yes it looks like the linux binary package is broken, but you must be on a different platform and the source package is ok.

PyPI has the two downloads:
```
json-table-schema-0.2.linux-i686.tar.gz built for Linux-3.13.0-24-generic-i686-with-glibc2.4  "dumb" binary 2015-05-11
json-table-schema-0.2.tar.gz Source 2015-05-13
```
https://pypi.python.org/pypi/json-table-schema/0.2

So if the binary can be removed from PyPI then I think this would sort things.

**Comment by scraperdragon** [comment]
Pretty sure you can't remove items from PyPI.
But perhaps an 0.2.1 which has no binary version would fix this?

@mk270 - could you make this happen?

**Comment by scraperdragon** [comment]
@pwalsh Could you be able to release a new, source-only version of json-table-schema-python with no other changes than the minor version number being bumped?

**Comment by pwalsh** [comment]
@scraperdragon sure, but first let me understand: is this a new problem? 

Because, I just took over the package from @mk270 a few weeks ago, but I haven't actually done anything with it apart from assume ownership on PyPI. The idea is that we will be replacing this with the newer work we have done for JSON table schema here: https://github.com/okfn/json-table-schema-py

Is this for messytables?

**Comment by pwalsh** [comment]
New source dist: https://pypi.python.org/pypi/json-table-schema/0.2.1

Please advise.

**Comment by pwalsh** [comment]
New source dist: https://pypi.python.org/pypi/json-table-schema/0.2.1

Please advise.

**Comment by davidread** [comment]
```
Downloading/unpacking json-table-schema>=0.2 (from messytables)
  Downloading json-table-schema-0.2.1.tar.gz
  Running setup.py egg_info for package json-table-schema
```
Yep, that appears to have fixed it. Cheers @pwalsh

**Comment by mk270** [comment]
Grand - can we close this off?

Also - maybe migrate the issue tracker to a different repo (I appreciate this is non-trivial) to reflect change in maintainership.

**Comment by pwalsh** [comment]
Hi @mk270 

I think steps to that could be:

1. You disable issues on this repo
2. You update the README with the following message (or something similar):

This repo is no longer maintained. The last version of this codebase is on [PyPI as v0.2.1 here](https://pypi.python.org/pypi/json-table-schema/0.2.1). Development of JSON Table Schema for python has moved to [Open Knowledge, in this repository](https://github.com/okfn/json-table-schema-py) and the [new issue tracker is located here](https://github.com/okfn/json-table-schema-py/issues)

**Comment by mk270** [comment]
added @pwalsh as collaborator

**Comment by pwalsh** [comment]
ok, I'll make those changes. Thanks @mk270 !
